apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-nginx:b26fb8040789c5e685c76ba4ee79a3d28d8f0482
        imagePullPolicy: IfNotPresent
        name: nginx-gateway
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        - name: http
          containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-svc
  namespace: app
spec:
  selector:
    app: nginx-gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
  type: NodePort
# docker run -d -p 80:80 -p 443:443 --restart=always --network=host joway/nginx-tcp-proxy:v2.0
