apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hexing
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexing
  template:
    metadata:
      labels:
        app: hexing
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-hexing:dbeab8cde2b949b5e3d0b8455c3d1ee4645f1a14
        imagePullPolicy: IfNotPresent
        name: hexing
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hexing-svc
  namespace: app
spec:
  selector:
    app: hexing
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
