apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homepage
  namespace: app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-homepage:09ba8f518cb84bbc221a0584fc21bbb35f6ddc4e
        imagePullPolicy: IfNotPresent
        name: homepage
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
  namespace: app
spec:
  selector:
    app: homepage
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
