apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: m2r
  namespace: app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: m2r
  template:
    metadata:
      labels:
        app: m2r
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-m2r:1359847566db6124c05ab56d9c302498cc311d96
        imagePullPolicy: IfNotPresent
        name: m2r
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: m2r-svc
  namespace: app
spec:
  selector:
    app: m2r
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
