apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netswatch
  namespace: app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: netswatch
  template:
    metadata:
      labels:
        app: netswatch
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-netswatch:25295e17c9f1f880fd5d30f91ad290ff15fcc315
        imagePullPolicy: IfNotPresent
        name: netswatch
        env:
          - name: BROKER_URL
            value: 'redis://redis:6379'
          - name: MYSQL_HOST
            value: 'mysql'
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
        ports:
        - name: web
          containerPort: 8000
          protocol: TCP
        resources: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netswatch-static
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netswatch-static
  template:
    metadata:
      labels:
        app: netswatch-static
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-netswatch:25295e17c9f1f880fd5d30f91ad290ff15fcc315
        imagePullPolicy: IfNotPresent
        name: netswatch-static
        ports:
        - name: web
          containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netswatch-celery-beat
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netswatch-celery-beat
  template:
    metadata:
      labels:
        app: netswatch-celery-beat
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-netswatch:25295e17c9f1f880fd5d30f91ad290ff15fcc315
        name: netswatch-celery-beat
        env:
          - name: BROKER_URL
            value: 'redis://redis:6379'
          - name: MYSQL_HOST
            value: 'mysql'
          - name: MODE
            value: 'CELERY_BEAT'
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netswatch-celery-worker
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netswatch-celery-worker
  template:
    metadata:
      labels:
        app: netswatch-celery-worker
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-netswatch:25295e17c9f1f880fd5d30f91ad290ff15fcc315
        name: netswatch-celery-worker
        env:
          - name: BROKER_URL
            value: 'redis://redis:6379'
          - name: MYSQL_HOST
            value: 'mysql'
          - name: MODE
            value: 'CELERY_WORKER'
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: netswatch-backend
  namespace: app
spec:
  selector:
    app: netswatch
  ports:
  - name: http
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: netswatch-static
  namespace: app
spec:
  selector:
    app: netswatch-static
  ports:
  - name: http
    port: 80
    targetPort: 80
