apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netswatch-web
  namespace: app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: netswatch-web
  template:
    metadata:
      labels:
        app: netswatch-web
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-netswatch-web:2b022deec800435ddb5628cc3a366250eb882302
        imagePullPolicy: IfNotPresent
        name: netswatch-web
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: netswatch-web
  namespace: app
spec:
  selector:
    app: netswatch-web
  ports:
  - name: http
    port: 80
    targetPort: 80
