apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-forward-proxy
  namespace: app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: nginx-forward-proxy
  template:
    metadata:
      labels:
        app: nginx-forward-proxy
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-nginx-forward-proxy:78a9a48655709900881e393bf8a8b1dd13ff5c31
        imagePullPolicy: IfNotPresent
        name: nginx-forward-proxy
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-forward-proxy-svc
  namespace: app
spec:
  selector:
    app: nginx-forward-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
