apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resume
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - image: gcr.io/jcloud-gce/github-joway-resume:1b70ed6493395b27237284fa040bb5842627868d
        imagePullPolicy: IfNotPresent
        name: resume
        readinessProbe:
          httpGet:
            path: /
            port: 4000
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: web
          containerPort: 4000
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: resume-svc
  namespace: app
spec:
  selector:
    app: resume
  ports:
  - name: http
    port: 80
    targetPort: 4000
  - name: https
    port: 443
    targetPort: 4000
