apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.11
        resources:
          limits:
            memory: 200Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
  namespace: app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
